// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nephele.BotManager.Repository;

#nullable disable

namespace Nephele.BotManager.Migrations.PostgreSql.Migrations
{
    [DbContext(typeof(BotManagerDbContext))]
    partial class BotManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder.Entity("Nephele.BotManager.Models.DomainModels.BotInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BotOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("BotOwner_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("CreateDate");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("DateStart");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Token");

                    b.Property<DateTime>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("BotInfo", (string)null);
                });

            modelBuilder.Entity("Nephele.BotManager.Models.DomainModels.BotOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("Endpoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying(300)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("BotOwner", (string)null);
                });

            modelBuilder.Entity("Nephele.BotManager.Models.DomainModels.BotOwner", b =>
                {
                    b.HasOne("Nephele.BotManager.Models.DomainModels.BotInfo", null)
                        .WithOne("BotOwner")
                        .HasForeignKey("Nephele.BotManager.Models.DomainModels.BotOwner", "Id")
                        .IsRequired();
                });

            modelBuilder.Entity("Nephele.BotManager.Models.DomainModels.BotInfo", b =>
                {
                    b.Navigation("BotOwner");
                });
#pragma warning restore 612, 618
        }
    }
}
