// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nephele.BotManager.Repository;

#nullable disable

namespace Nephele.BotManager.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(BotManagerDbContext))]
    [Migration("20260212165438_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder.Entity("Nephele.BotManager.Models.DomainModels.BotInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BotOwnerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BotOwner_id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("DateStart");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Token");

                    b.Property<DateTime>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.ToTable("BotInfo", (string)null);
                });

            modelBuilder.Entity("Nephele.BotManager.Models.DomainModels.BotOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Endpoint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("Id");

                    b.ToTable("BotOwner", (string)null);
                });

            modelBuilder.Entity("Nephele.BotManager.Models.DomainModels.BotOwner", b =>
                {
                    b.HasOne("Nephele.BotManager.Models.DomainModels.BotInfo", null)
                        .WithOne("BotOwner")
                        .HasForeignKey("Nephele.BotManager.Models.DomainModels.BotOwner", "Id")
                        .IsRequired();
                });

            modelBuilder.Entity("Nephele.BotManager.Models.DomainModels.BotInfo", b =>
                {
                    b.Navigation("BotOwner");
                });
#pragma warning restore 612, 618
        }
    }
}
